include ../qbee-key.inc

DISTRO = "xwing"
DISTRO_NAME = "Frank X-Wing"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "X-Wing"

DISTRO_FEATURES:append = " systemd rauc usrmerge opengl"
DISTRO_FEATURES:remove = " sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_login_manager = "shadow-base"
VIRTUAL-RUNTIME_dev_manager = "udev"

# SDIMG_ROOTFS_TYPE="ext4"
ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi-v7_6.12"
hostname:pn-base-files = "bb8"

IMAGE_OVERHEAD_FACTOR = "1.0"
IMAGE_ROOTFS_EXTRA_SPACE = "0"