require conf/machine/raspberrypi.conf

MACHINEOVERRIDES =. "raspberrypi-bb8:"

# allinea upstream kernel
KERNEL_DEVICETREE = "broadcom/bcm2835-rpi-b.dtb"
KERNEL_IMAGETYPE = "zImage"

# allinea meta-raspberrypi boot logic
RPI_KERNEL_DEVICETREE = "bcm2835-rpi-b.dtb"

# override boot files completamente (evita roba zero)
IMAGE_BOOT_FILES = "bcm2835-rpi-b.dtb;${KERNEL_DEVICETREE} \
                    ${KERNEL_IMAGETYPE}"