

DEFAULTTUNE ?= "arm1176jzfshf"

require conf/machine/include/tune-arm1176jzf-s.inc
include conf/machine/include/rpi-base.inc

SDIMG_KERNELIMAGE  ?= "kernel.img"
UBOOT_MACHINE = "rpi_config"
SERIAL_CONSOLES ?= "115200;ttyAMA0"

ARMSTUB ?= "armstub.bin"

MACHINEOVERRIDES =. "raspberrypi-bb8:"

# allinea upstream kernel
KERNEL_IMAGETYPE = "uImage"
UBOOT_ENTRYPOINT = "0x00008000"
UBOOT_LOADADDRESS = "0x00008000"
KERNEL_EXTRA_ARGS += "LOADADDR=${UBOOT_ENTRYPOINT}"

# allinea meta-raspberrypi boot logic
RPI_KERNEL_DEVICETREE = "bcm2835-rpi-b.dtb"
PREFERRED_PROVIDER_virtual/kernel = "linux-master"
RPI_USE_U_BOOT = "1"
RPI_KERNEL_DEVICETREE_OVERLAYS = ""
